### ISSUE TITLE
🐛 [Bug] 添加新网站后wwwroot目录权限异常

### ISSUE THREAD

**Issue by Super-Pig-Pig** [TheTNB/panel#102]
### 在提问之前 (Before Asking)

- [x] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在升级之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

11.2

### 耗子面板版本 (HaoZi Panel Version)

2.2.6

### 描述问题 (Describe The Problem)

面板安装完OpenResty，新建网站后，wwwroot目录以及子目录权限变为0000。

https://github.com/TheTNB/panel/assets/75372669/fbf62f1a-e271-49b7-ac57-a5f8098c5178

### 如何复现 (How To Reproduce)

新建网站后，wwwroot目录以及子目录权限即可变为0000

### 预期行为 (Expected Behavior)

N/A

**Comment by devhaozi** [comment]
测试 v2.2.7 是否解决？

**Comment by Super-Pig-Pig** [comment]
> 测试 v2.2.7 是否解决？

经过测试，v2.2.7已解决此问题~
![BFCF208B215080CF12F9F3F1617B760D](https://github.com/TheTNB/panel/assets/75372669/ad2e4b98-acde-403d-89ae-b80523c31357)
