### ISSUE TITLE
✨ [Feature] 分离插件功能

### ISSUE THREAD

**Issue by stevessr** [TheTNB/panel#114]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

将plugins部分分离为单独的golang库，便于添加插件

### 工作流程 (WorkFlow)

1. 分离plugins
2. 添加plugins贡献标准
3. ...

**Comment by devhaozi** [comment]
可供参考的实现
https://github.com/FloatTech/ZeroBot-Plugin

**Comment by devhaozi** [comment]
尝试做了一下，发现很不好实现且很不方便管理，暂时不考虑了，等 go 官方把插件系统修完善了再说。
（不过会尽可能优化目前的实现，尽量方便添加新插件）
