### ISSUE TITLE
✨ [Feature] 希望支持 OpenLiteSpeed 

### ISSUE THREAD

**Issue by weiyidu** [TheTNB/panel#123]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

希望支持 OpenLiteSpeed 

### 工作流程 (WorkFlow)

1. 新建文件 ....
2. 添加函数 ....
3. ...

**Comment by devhaozi** [comment]
OLS貌似不需要面板？它自带的那个就挺好用的。

**Comment by weiyidu** [comment]
> OLS貌似不需要面板？它自带的那个就挺好用的。

自带的不支持debian

**Comment by devhaozi** [comment]
暂时关闭了，未来应该会优化容器那块添加OLS可以直接使用。

**Comment by realstephenzhao** [comment]
居然两年前就有人提出这个功能请求了，但是现在还是没有开发。
---
OpenLiteSpeed 自带的那个配置面板，怎么说呢，根本不适合普通人用。

<img width="725" height="439" alt="Image" src="https://github.com/user-attachments/assets/d5cbe1dc-4947-4d8c-97e4-b7d6b68f2559" />

---
我希望仓库管理者能重开这个功能请求 issue。@devhaozi @h2zi

**Comment by h2zi** [comment]
> ## 居然两年前就有人提出这个功能请求了，但是现在还是没有开发。
> OpenLiteSpeed 自带的那个配置面板，怎么说呢，根本不适合普通人用。
> 
> <img alt="Image" width="725" height="439" src="https://private-user-images.githubusercontent.com/7487908/588992274-d5cbe1dc-4947-4d8c-97e4-b7d6b68f2559.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzgxNzIzNjcsIm5iZiI6MTc3ODE3MjA2NywicGF0aCI6Ii83NDg3OTA4LzU4ODk5MjI3NC1kNWNiZTFkYy00OTQ3LTRkOGMtOTdlNC1iN2Q2YjY4ZjI1NTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDUwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA1MDdUMTY0MTA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzllMDY4MjMyYjI1NDA2MWI5NDg4YzFiZTUxNDcxY2VhNzk0YjQ5MDNiMDNkMTAzNjRhMWNkNWNkZDExZTZkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.YKfqSfgqW9DLr9g62U3Zo2ERFFqHaqpYIffLqNUHwhc">
> 我希望仓库管理者能重开这个功能请求 issue。[@devhaozi](https://github.com/devhaozi) [@h2zi](https://github.com/h2zi)

在 AcePanel 3.0 开发的时候曾考虑过添加 OLS 支持，但由于其配置文件过于复杂，性能强依赖那个 lsphp 且对 include 等指令的支持极弱，最后放弃了。
未来可能会优先添加 Caddy 支持。

**Comment by h2zi** [comment]
v3.3.6 已添加 OLS 支持，同时适配了核心的 LSAPI 以及 LSCache 功能，欢迎测试 @realstephenzhao @weiyidu
