### ISSUE TITLE
🐛 [Bug] 点击任务中心就会登出

### ISSUE THREAD

**Issue by jackmamaa** [TheTNB/panel#138]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在升级之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

12

### 耗子面板版本 (HaoZi Panel Version)

v2.2.20

### 描述问题 (Describe The Problem)

进入登录页面会提示一个会话过期提示，登录进去后会直接再次登出，这次会有4个会话过期提示框，再次登录就登进去了，然后点击任务中心会继续循环上述问题。

https://github.com/TheTNB/panel/assets/119478410/0f6ec7f0-fcca-4279-b8fd-635bac4364de

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题
问题描述有了

### 预期行为 (Expected Behavior)

解决问题

**Comment by devhaozi** [comment]
浏览器支持cookie吗？是不是把cookie禁用了

**Comment by jackmamaa** [comment]
![Uploading 20240711152031.png…]()

**Comment by jackmamaa** [comment]
![20240711152031](https://github.com/TheTNB/panel/assets/119478410/5431a611-a968-4ab2-873d-bcc5b1742f6d)

**Comment by devhaozi** [comment]
> ![20240711152031](https://private-user-images.githubusercontent.com/119478410/347720632-5431a611-a968-4ab2-873d-bcc5b1742f6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2ODI5OTAsIm5iZiI6MTcyMDY4MjY5MCwicGF0aCI6Ii8xMTk0Nzg0MTAvMzQ3NzIwNjMyLTU0MzFhNjExLWE5NjgtNGFiMi04NzNkLWJjYzViMTc0MmY2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQwNzI0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNDQ3MDY1MjUwMDFhODA1ZWM5NGRkM2VlOWEzYjM4MmE3YTNiZTk1OGYyMGEzMTUxYzdiY2Y2ZGY4MDQ1YjM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CI9pbaZGgIkP6GJ7jJsMkolh3sgxcvdylD_VXbTuO9E)

目前测试发现这个问题会在使用代理的时候出现，可以把代理关掉试试。
在研究怎么解决中。。。

**Comment by jackmamaa** [comment]
关了代理一样，刷新就强制登出，提示会话过期。

**Comment by devhaozi** [comment]
> 关了代理一样，刷新就强制登出，提示会话过期。

加群私发面板信息看看

**Comment by devhaozi** [comment]
refer: https://github.com/goravel/framework/pull/550
