### ISSUE TITLE
🐛 [Bug]  面板IPV6访问问题

### ISSUE THREAD

**Issue by jarodvip** [TheTNB/panel#154]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [ ] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [ ] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在升级之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

11

### 耗子面板版本 (HaoZi Panel Version)

2.2.27

### 描述问题 (Describe The Problem)

面板安装后默认登录地址是IPV6，可我本地网络只支持IPV4,如何更改面板访问地址为IPV4

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 预期行为 (Expected Behavior)

希望能尽快给解决办法

**Comment by devhaozi** [comment]
实际上是双栈监听的，你可以自行从v4地址访问。
