### ISSUE TITLE
✨ [Feature] 能否支持sysvinit安装,容器设备不能使用systemd

### ISSUE THREAD

**Issue by candywzt** [TheTNB/panel#196]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

能否支持sysvinit安装,容器设备不能使用systemd

### 工作流程 (WorkFlow)

我是小白,我不会写

**Comment by devhaozi** [comment]
暂无计划，sysvinit是早期的技术了，现代系统基本都用systemd。
