### ISSUE TITLE
✨ [Feature] 容器页面

### ISSUE THREAD

**Issue by devhaozi** [TheTNB/panel#21]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

计划开发容器页面

### 工作流程 (WorkFlow)

None

**Comment by xiezh123** [comment]
[https://podman.io/docs/installation](url)可以另外添加对podman的支持吗？不想使用docker

**Comment by devhaozi** [comment]
> [https://podman.io/docs/installation](url)可以另外添加对podman的支持吗？不想使用docker

可以按模板新开个 issue

**Comment by devhaozi** [comment]
github.com/containers/podman/blob/main/pkg/bindings 可用，但是导入 100 多个包给我人看傻了，计划自行实现一个包替代之。

**Comment by devhaozi** [comment]
> github.com/containers/podman/blob/main/pkg/bindings 可用，但是导入 100 多个包给我人看傻了，计划自行实现一个包替代之。

docker 的 SDK 也是一样抽象，自带 200 多个包。找到一个可用的第三方实现 github.com/fsouza/go-dockerclient 测试中。。。
