### ISSUE TITLE
🐛 [Bug] phpMyAdmin 源码 checksum 校验失败，文件可能被篡改或不完整，已终止操作

### ISSUE THREAD

**Issue by romekic** [TheTNB/panel#243]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了 README 中除版本记录以外的所有内容 (I've read everything in the README except the version notes)
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备 (I spend at least 5 minutes thinking and preparing before asking a question)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [X] 问题是在升级之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

12.7

### 耗子面板版本 (HaoZi Panel Version)

v2.2.27

### 描述问题 (Describe The Problem)

安装插件 phpMyAdmin 出现错误，被雷池防火墙拦截checksum.txt

### 如何复现 (How To Reproduce)

安装插件 phpMyAdmin 出现错误

### 预期行为 (Expected Behavior)

防火墙修复

### 相关日志 (Related Logs)

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2024-10-11 21:02:29--  https://dl.cdn.haozi.net/panel/phpmyadmin/phpMyAdmin-5.2.1-all-languages.zip
Resolving dl.cdn.haozi.net (dl.cdn.haozi.net)... 180.163.146.83
Connecting to dl.cdn.haozi.net (dl.cdn.haozi.net)|180.163.146.83|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-10-11 21:02:31 ERROR 403: Forbidden.

Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/root/.wget-hsts'. HSTS will be disabled.
--2024-10-11 21:02:31--  https://dl.cdn.haozi.net/panel/phpmyadmin/phpMyAdmin-5.2.1-all-languages.zip.checksum.txt
Resolving dl.cdn.haozi.net (dl.cdn.haozi.net)... 180.163.146.83
Connecting to dl.cdn.haozi.net (dl.cdn.haozi.net)|180.163.146.83|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-10-11 21:02:32 ERROR 403: Forbidden.

sha256sum: phpMyAdmin-5.2.1-all-languages.zip.checksum.txt: no properly formatted checksum lines found
+----------------------------------------------------
错误：phpMyAdmin 源码 checksum 校验失败，文件可能被篡改或不完整，已终止操作

### 截图 (Screenshots)

![image](https://github.com/user-attachments/assets/4ced1ee3-eb81-4bfe-a4fd-10c098b589ca)

**Comment by devhaozi** [comment]
这两天在测试重构的新版本，旧版本的下载目前停了。

**Comment by devhaozi** [comment]
另外暂时不建议使用旧版本了，因为无法直接升级到即将发布的新版本。

**Comment by romekic** [comment]
好的
