### ISSUE TITLE
🐛 [Bug] 

### ISSUE THREAD

**Issue by renfu-her** [TheTNB/panel#337]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [X] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Ubuntu

### 操作系统版本 (Operating System Version)

22.04

### 耗子面板版本 (Rat Panel Version)

2.3.17

### 描述问题 (Describe The Problem)

安装应用 Percona (MySQL) | 已失败

![image](https://github.com/user-attachments/assets/c3bf4e19-d0b5-4c86-83f2-3474de1c9504)

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 预期行为 (Expected Behavior)

想要知道如何處理

### 截图 (Screenshots)

![image](https://github.com/user-attachments/assets/bc0d366d-2f1a-45cd-938e-d303e9d0b0a1)

**Comment by devhaozi** [comment]
cpu缺少sse 4.2指令集支持，建议检查一下，如果买的服务器的话工单问问。

**Comment by devhaozi** [comment]
> cpu缺少sse 4.2指令集支持，建议检查一下，如果买的服务器的话工单问问。

cpu是支持的，问题大概率出在虚拟化上。
