### ISSUE TITLE
🐛 [Bug] 文件管理器和Fail2ban Bug

### ISSUE THREAD

**Issue by BigFF** [TheTNB/panel#443]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

12

### 耗子面板版本 (Rat Panel Version)

2.3.23

### 描述问题 (Describe The Problem)

1. 面板安装路径不是默认的 /www 进入面板文件管理器会默认进入 /www 导致报错
2. fail2ban 如果修改默认ssh端口之后无法正常工作，没办法识别当前ssh端口

### 如何复现 (How To Reproduce)

文件管理器Bug
1. 安装面板
2. 设置安装目录是 /data
3. 面板文件管理器就会报错

Fail2ban Bug
1. 修改sshd端口号
2. 安装面板
3. 安装fail2ban插件
4. 插件无法拦截ssh爆破

### 预期行为 (Expected Behavior)

1. 文件管理器可以识别面板的安装目录配置
2. fail2ban插件安装时识别ssh端口号，管理页面可以修改端口号

**Comment by devhaozi** [comment]
1. 后续版本优化
2. 正常情况，端口改了要对应修改fail2ban配置
