### ISSUE TITLE
🐛 [Bug] 无法删除网站和证书

### ISSUE THREAD

**Issue by vimbackground** [TheTNB/panel#445]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [X] 我没有改动过面板及系统的任何文件 (I have not changed any files of the panel and system)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 操作系统 (Operating System)

Debian

### 操作系统版本 (Operating System Version)

12

### 耗子面板版本 (Rat Panel Version)

2.3.23

### 描述问题 (Describe The Problem)

测试网站时，在网站设置的HTTPS标签页，点击了右上角的“一键签发证书”。然后在打“总开关”时报错，提示“SSLCertificate为必填字段”。

然后想删除这个测试站，重新建立一个网站。然后出现以下情况：

1. 无法删除网站，提示“绑定证书，请先删除证书”
2. 证书列表处找不到删除证书的地方

请问这是什么情况，可以怎么处理？

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 预期行为 (Expected Behavior)

1. 系统提示后续可以怎么处理
2. 能简单方便的删除已有的证书和网站

### 相关日志 (Related Logs)

wwwlogs下的日志文件内容为空

**Comment by vimbackground** [comment]
去掉这个自动回复吧，先看看问题是否已经内容够了。

> Hi @vimbackground 👋
> 
> 我们认为您的反馈非常有价值！欢迎提交 PR，请包含相应的测试用例、文档等，并确保 CI 通过，感谢和期待您的贡献！ We think your feedback is very valuable! Welcome to submit a PR, please include test cases, documentation, etc., and ensure that the CI is passed, thank you and look forward to your contribution!
> 
> ![干](https://private-user-images.githubusercontent.com/115467771/259498447-fb04debf-3f4c-4fac-a0b8-c3455f8e57a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNTI1MzMsIm5iZiI6MTczNDI1MjIzMywicGF0aCI6Ii8xMTU0Njc3NzEvMjU5NDk4NDQ3LWZiMDRkZWJmLTNmNGMtNGZhYy1hMGI4LWMzNDU1ZjhlNTdhMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwODQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMjEyYWQxZjkxODAxYjI3OWI2MTI1YzlkNjc5Yjk1YTJhY2I4YjFiMzMwOTFjYjBkNDEyYzRhMzU4M2JkNTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ed1KzDatyWJKguFfkqiSHp2weu2QkcIIbUI2Upz6C7M)

**Comment by devhaozi** [comment]
可以加群私发下面板信息这边看看

**Comment by vimbackground** [comment]
日志文件大小都为0，怎么整

![Snipaste_2024-12-15_18-11-02](https://github.com/user-attachments/assets/adf283bb-f6d3-4958-9c22-51c2d9d3d80c)

**Comment by devhaozi** [comment]
![image](https://github.com/user-attachments/assets/7fe0bd91-7cc7-4ddb-9f84-30f3f0acc81c)

这里没有证书吗

**Comment by vimbackground** [comment]
有，但是无法做任何操作

![Snipaste_2024-12-15_19-14-57](https://github.com/user-attachments/assets/099e78e3-d343-4dc3-bf9b-5f7f21411860)

**Comment by devhaozi** [comment]
> firefox 128.5.2esr (64 位)

测试没复现，感觉是屏幕太小了？

**Comment by vimbackground** [comment]
> > firefox 128.5.2esr (64 位)
> 
> 测试没复现，感觉是屏幕太小了？或者有什么别的拦截插件把右边的操作按钮全隐藏了

经测试，确实是这个问题，显示器设置了缩放125%。调小浏览器显示比例后，证书页后面的删除就出现了。

很少碰到这种情况，明明内容没有显示，浏览器没出现左右滚动条，页面也没有自动调整……

不是什么大问题，但确实也是个问题：）
