### ISSUE TITLE
🐛 [Bug] 无法安装php的redis扩展，php8.2、php8.3、php8.4都不行

### ISSUE THREAD

**Issue by vimbackground** [TheTNB/panel#446]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [X] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 操作系统及版本 (OS Version)

Debian

### 面板版本 (Panel Version)

2.3.23

### 描述问题 (Describe The Problem)

如题

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 预期行为 (Expected Behavior)

正常安装，正常使用

### 还有别的吗 (Anything Else)

很喜欢耗子面板这种简洁聚集的风格，如果好用话，准备把宝塔给换掉，但好像小问题多了点……

**Comment by devhaozi** [comment]
日志呢？
![a919ae44fed09db9b4dd79933b3b6681](https://github.com/user-attachments/assets/0ce7a32d-cc79-4bef-91fc-5bec1d0ed376)

**Comment by vimbackground** [comment]
wwwlogs里的日志大小都为0，请问，是这里的日志吗？还是其它哪里的日志文件？

![Snipaste_2024-12-15_18-11-02](https://github.com/user-attachments/assets/094b9f7f-68e5-434e-8fff-0c19365ad283)

**Comment by devhaozi** [comment]
菜单 后台任务->面板任务 把redis拓展安装日志贴出来

**Comment by vimbackground** [comment]
日志信息如下：

日志

phpredis-6.1.0/redis_array_impl.c

phpredis-6.1.0/redis_array_impl.h

phpredis-6.1.0/redis_array_legacy_arginfo.h

phpredis-6.1.0/redis_cluster.c

phpredis-6.1.0/redis_cluster.h

phpredis-6.1.0/redis_cluster.stub.php

phpredis-6.1.0/redis_cluster_arginfo.h

phpredis-6.1.0/redis_cluster_legacy_arginfo.h

phpredis-6.1.0/redis_commands.c

phpredis-6.1.0/redis_commands.h

phpredis-6.1.0/redis_legacy_arginfo.h

phpredis-6.1.0/redis_sentinel.c

phpredis-6.1.0/redis_sentinel.h

phpredis-6.1.0/redis_sentinel.stub.php

phpredis-6.1.0/redis_sentinel_arginfo.h

phpredis-6.1.0/redis_sentinel_legacy_arginfo.h

phpredis-6.1.0/redis_session.c

phpredis-6.1.0/redis_session.h

phpredis-6.1.0/rpm/

phpredis-6.1.0/rpm/README.md

phpredis-6.1.0/sentinel.md

phpredis-6.1.0/sentinel_library.c

phpredis-6.1.0/sentinel_library.h

phpredis-6.1.0/serialize.list

phpredis-6.1.0/tests/

phpredis-6.1.0/tests/RedisArrayTest.php

phpredis-6.1.0/tests/RedisClusterTest.php

phpredis-6.1.0/tests/RedisSentinelTest.php

phpredis-6.1.0/tests/RedisTest.php

phpredis-6.1.0/tests/SessionHelpers.php

phpredis-6.1.0/tests/TestRedis.php

phpredis-6.1.0/tests/TestSuite.php

phpredis-6.1.0/tests/getSessionData.php

phpredis-6.1.0/tests/make-cluster.sh

phpredis-6.1.0/tests/mkring.sh

phpredis-6.1.0/tests/regenerateSessionId.php

phpredis-6.1.0/tests/startSession.php

phpredis-6.1.0/tests/users.acl

phpredis-6.1.0/tests/vg.supp

Configuring for:

PHP Api Version:         20220829

Zend Module Api No:      20220829

Zend Extension Api No:   420220829

checking for grep that handles long lines and -e... /bin/grep

checking for egrep... /bin/grep -E

checking for a sed that does not truncate output... /bin/sed

checking for pkg-config... /bin/pkg-config

checking pkg-config is at least version 0.9.0... yes

checking for cc... cc

checking whether the C compiler works... yes

checking for C compiler default output file name... a.out

checking for suffix of executables...

checking whether we are cross compiling... no

checking for suffix of object files... o

checking whether the compiler supports GNU C... yes

checking whether cc accepts -g... yes

checking for cc option to enable C11 features... none needed

checking how to run the C preprocessor... cc -E

checking for icc... no

checking for suncc... no

checking for system library directory... lib

checking if compiler supports -Wl,-rpath,... yes

checking build system type... x86_64-pc-linux-gnu

checking host system type... x86_64-pc-linux-gnu

checking target system type... x86_64-pc-linux-gnu

checking for PHP prefix... /www/server/php/82

checking for PHP includes... -I/www/server/php/82/include/php -I/www/server/php/82/include/php/main -I/www/server/php/82/include/php/TSRM -I/www/server/php/82/include/php/Zend -I/www/server/php/82/include/php/ext -I/www/server/php/82/include/php/ext/date/lib

checking for PHP extension directory... /www/server/php/82/lib/php/extensions/no-debug-non-zts-20220829

checking for PHP installed headers prefix... /www/server/php/82/include/php

checking if debug is enabled... no

checking if zts is enabled... no

checking for gawk... no

checking for nawk... nawk

checking if nawk is broken... no

checking whether to enable redis support... yes, shared

checking whether to enable sessions... yes

checking whether to enable json serializer support... yes

checking whether to enable igbinary serializer support... yes

checking whether to enable msgpack serializer support... no

checking whether to enable lzf compression... no

checking use system liblzf... no

checking whether to enable Zstd compression... yes

checking use system libzstd... yes

checking whether to enable lz4 compression... no

checking use system liblz4... no

checking for hash includes... /www/server/php/82/include/php

checking for json includes... /www/server/php/82/include/php

checking for redis json support... enabled

checking for igbinary includes... configure: error: Cannot find igbinary.h

make: *** No targets specified and no makefile found.  Stop.

+----------------------------------------------------

| 错误：PHP-82 phpredis 编译失败

| Error: PHP-82 phpredis 编译失败

| 可截图错误信息寻求帮助，或者联系面板官方支持。

| Take a screenshot of the error message for help, or contact the panel official support.

+----------------------------------------------------

| Kernel: Linux vdb 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

| CPU: QEMU Virtual CPU version 2.5+ | Arch: x86_64 | Core: 2

| OS: Debian GNU/Linux 12 (bookworm) | Bit: 64-bit | Mem: 1867 | Swap: 974 | gcc: 12.2.0 | cmake: 3.25.1

+----------------------------------------------------
