### ISSUE TITLE
🐛 [Bug] 面板无法识别系统已经安装的docker

### ISSUE THREAD

**Issue by vimbackground** [TheTNB/panel#455]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [ ] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [ ] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 系统版本 (OS Version)

debian12

### 面板版本 (Panel Version)

2.3.23

### 描述问题 (Describe The Problem)

系统已经安装了docker-ce，面板后台点击容器时，仍然提示“容器引擎 Docker / Podman 未安装”。

请问这是什么情况，是对docker的版本啥的有具体要求吗？

### 如何复现 (How To Reproduce)

1. 安装面板
2. 设置 '...'
3. 点击 '...'
4. 出现问题

### 截图 (Screenshots)

![Snipaste_2024-12-17_00-01-26](https://github.com/user-attachments/assets/eccf182b-951b-468d-af20-2740ae7675e2)

**Comment by vimbackground** [comment]
> 是的，无法直接识别自带的，可以通过下面的命令标记已安装
> 
> ```
> panel-cli app write docker stable 27.3
> ```

好吧，虽然不是太方便，也不是啥大问题。期待后续版本能在panel界面上有些简单的操作方法，比如给个按钮检测啥的。

另外，在cli里面解决上述问题后，想删除在panel里另外安装的podman，无法删除，提示“请求返回异常：应用 Podman 与 Docker 不能共存”。点击podman的服务管理，服务处于关闭状态。

虽然docker已经正常使用，无视podman就好。但多少有些强迫症，希望解决一下这个问题。

**Comment by devhaozi** [comment]
> > 是的，无法直接识别自带的，可以通过下面的命令标记已安装
> > ```
> > panel-cli app write docker stable 27.3
> > ```
> 
> 好吧，虽然不是太方便，也不是啥大问题。期待后续版本能在panel界面上有些简单的操作方法，比如给个按钮检测啥的。
> 
> 另外，在cli里面解决上述问题后，想删除在panel里另外安装的podman，无法删除，提示“请求返回异常：应用 Podman 与 Docker 不能共存”。点击podman的服务管理，服务处于关闭状态。
> 
> 虽然docker已经正常使用，无视podman就好。但多少有些强迫症，希望解决一下这个问题。

小问题，可以这样解决

```
apt-get remove podman podman-compose podman-docker containers-storage -y
panel-cli app remove podman
```

**Comment by devhaozi** [comment]
在面板安装脚本层面进行了优化，安装后会自动检测是否安装了docker/podman并标记对应的安装状态。
