### ISSUE TITLE
🐛 [Bug] 2.4.0 无法完成安装

### ISSUE THREAD

**Issue by BigFF** [TheTNB/panel#475]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了现有的 Issues, Discussions 和 Google (I've searched the existing Issues, Discussions and Google)
- [X] 我已经阅读了文档中除版本记录以外的所有内容 (I've read everything in the documentation except the version notes)
- [X] 这个问题可以被稳定复现 (The problem can be stably reproduced)
- [X] 问题是在更新之后产生的 (The problem is generated after upgrading)

### 系统版本 (OS Version)

debian 12

### 面板版本 (Panel Version)

2.4.0

### 描述问题 (Describe The Problem)

全新的系统首次安装2.4.0提示找不到相关表
历史旧版本升级，从2.3.8升级到2.4.0暂未发现问题

日志：
2024-12-29 14:45:33 (4.08 MB/s) - '/etc/systemd/system/panel.service' saved [352/352]

**panic: 初始化失败：SQL logic error: no such table: settings (1)**

goroutine 1 [running]:
main.main()
	/home/runner/work/panel/panel/cmd/cli/main.go:35 +0x96
Created symlink /etc/systemd/system/multi-user.target.wants/panel.service -> /etc/systemd/system/panel.service.
+----------------------------------------------------
| 耗子面板安装脚本
| Rat Panel install script
+----------------------------------------------------
| Copyright © 2022-2024 耗子科技 All rights reserved.
+----------------------------------------------------
**面板安装成功！**
+----------------------------------------------------
**panic: 获取管理员信息失败：SQL logic error: no such table: users (1)**

### 如何复现 (How To Reproduce)

1. 安装全新debian 12 x64
2. 执行安装面板脚本
3. 出现问题

### 预期行为 (Expected Behavior)

* 正常完成安装
* 如涉及库表的操作，其他逻辑是否影响可评估
* 安装提供指定版本号选择（近5个或指定？），以便出现问题时可以继续使用旧版本安装

**Comment by devhaozi** [comment]
复现，修复中

**Comment by devhaozi** [comment]
在 2.4.1 修复，运行卸载脚本清理后重新安装即可。

```bash
curl -fsLm 10 -o uninstall.sh https://dl.cdn.haozi.net/panel/uninstall.sh && bash uninstall.sh
```
