### ISSUE TITLE
✨ [Feature] PHP 拓展添加 Swow 和 Swoole

### ISSUE THREAD

**Issue by devhaozi** [TheTNB/panel#66]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

如题

### 工作流程 (WorkFlow)

待定

### 还有别的吗 (Anything Else)

这俩玩意更新挺快的，但是目前面板的 PHP 拓展没有版本管理机制，考虑日后添加版本管理？

**Comment by devhaozi** [comment]
a86d8a7490e28f5a15b848e40408ad2f971b13a2

**Comment by gxggxl** [comment]
没有 sg11 拓展
