### ISSUE TITLE
✨ [Feature] 需求：软件安装进度，php扩展一键安装

### ISSUE THREAD

**Issue by sixgodfan** [TheTNB/panel#77]
### 在提问之前 (Before Asking)

- [X] 我已经搜索了全部 Issues 和 Commits (I have searched all Issues and Commits)
- [X] 它们当中没有我将要提交的新功能 (None of them have new feature that I'm going to submit)

### 描述功能 (Describe Feature)

面板安装完成我安装php8.3秒安装，点击日志提示 网络问题。继续安装其他软件，等半天也没完成，没进度看的难受也不知道啥情况。只能卸载……2核3GB，今日安装了不下四五个面板都正常使用的，期待耗子panel优化！
PHP 扩展常用的如bcmath gmp pcntl fileinfo之类的希望能想bt一样点击安装即可。没用还不知道……

### 工作流程 (WorkFlow)

1. 新建文件 ....
2. 添加函数 ....
3. ...

**Comment by devhaozi** [comment]
软件中的安装日志即是进度，方便的话可以贴一下提示网络问题的截图看看。至于 PHP 拓展，目前有计划添加更多拓展，不过优先级不是很高。
